### ISSUE TITLE
create a script for logging requests from google gemini

### ISSUE THREAD

**Issue by abubakarsohail** [MagnivOrg/prompt-layer-js#48]
The purpose of this task is to create a script for logging requests made via google gemini. This task will include serialization of data to be sent over network.

**Comment by abubakarsohail** [comment]
https://gist.github.com/abubakarsohail/b3eeb353ec4c5f01d3e742724d4390c6

**Comment by buckyroberts** [comment]
The code looks good but can you just include a 5 second Loom of this working? I'm not sure what environment you are using, which directory you are running it from, etc... but as long as it's working then it's good by me.
